### ISSUE TITLE
[Probably not BUG] Deleting community admin user

### ISSUE THREAD

**Issue by michaltarana** [rspace-os/rspace-docker#2]
When a sysadmin creates a community admin account, it cannot be deleted. It is mentioned in the documentation. However, in the case that the sysadmin makes a mistake by assigning the community admin role to the new account, this username will be blocked forever. Is that right? Is there any way to circumvent this feature?

Assume that the instance has a username convention first_name.last_name.

1. Log in as a sysadmin
2. Go to 'System'
3. Click on 'Create Account'
4. Create an account for John Doe with username john.doe
5. Forget for a while that he is supposed to be a PI and make him a Community Admin
6. Click on 'Save'
7. Realize the mistake and in the 'System->Users' check the user account.
8. It is not possible to promote it to PI
9. Try to delete the account (assuming that it is allowed in the deployment.properties).
10. Notification of successful deletion will appear.
11. The user still exists in the list of accounts (as mentioned in the documentation).
12. It is not possible to create another user john.doe with the right role (PI, for instance).

**Expected behavior**
1. If the Admin user cannot be deleted, I would expect the 'Delete' item in the 'Actions' menu to be inactive.
2. If the user cannot be deleted, I would not expect the successful web notification to appear.

Is there anything on the backend I can do to release the username to create another account with the right role?

**Desktop (please complete the following information):**
 - OS: Linux
 - chrome
 - 125

**Additional context**
This is probably not a bug. It just seems that some mistakes are not reversible. Is that really so?

**Comment by mKowalski256** [comment]
Thank you for raising the issue with all the details. 

For context: 'Delete user' functionality that can be enabled in deployment.properties is supposed to only work for newly created users who were not involved in any group/community structures, etc. Basically it's to support deletion of users who were created by mistake during system setup page, and didn't yet start using their accounts. Users who did start using their account cannot be fully deleted - for them you can only disable the account / clear the profile details, but that will not release the username (i.e. username will be blocked forever).

Still, in your particular scenario you're trying to delete newly created Community Admin - and that is supposed to work. I've tried to reproduce the issue, but it actually does work fine on my test instance - I can delete Community Admin, whether one assigned to an existing community, or not. Can you attach a fragment of error.log that is showing what happens during user deletion attempt?

**Comment by tuxRamon** [comment]
Hi, 

If you add sysadmin.delete.user=true to your deployment.properties file and then restart the rspace-app docker container, it should work when you try to delete the user again.

Furthermore, this essentially can be split into two bugs:

- Bug 1: sysadmin.delete.user= value was not present in deployment.properties file in the rspace-docker repo. This has been fixed now (by default the value is kept as false, but it is much easier to change now to true compared to before). Fixed with commit 38bec70 on rspace-docker

- Bug 2: There is a bug in RSpace where the delete button is not grayed out if account deletion is disabled. A ticket has been raised for this - https://github.com/rspace-os/rspace-web/issues/46

Thanks,
Ramon
